const DESTINATIONS = [
  {
    id: 'indianapolis',
    name: 'Indianapolis',
    state: 'IN',
    driveHours: 1.5,
    anchor: 'Indianapolis Motor Speedway',
    description: 'Racing history, a revived downtown, and some of the best food in the Midwest — all without the big-city chaos.',
    vibes: ['History', 'Arts', 'Food'],
  },
  {
    id: 'cincinnati',
    name: 'Cincinnati',
    state: 'OH',
    driveHours: 2,
    anchor: 'Over-the-Rhine Historic District',
    description: 'Victorian row houses, craft breweries on every block, and Cincinnati chili — a city with a personality all its own.',
    vibes: ['History', 'Arts', 'Food'],
  },
  {
    id: 'detroit',
    name: 'Detroit',
    state: 'MI',
    driveHours: 2,
    anchor: 'Motown Museum',
    description: "One of America's great comeback stories, with art, music, and food that punch well above their weight.",
    vibes: ['History', 'Arts', 'Music', 'Food'],
  },
  {
    id: 'columbus',
    name: 'Columbus',
    state: 'OH',
    driveHours: 2.5,
    anchor: 'Short North Arts District',
    description: 'A walkable arts corridor, James Beard–worthy restaurants, and a college city that got unexpectedly cool.',
    vibes: ['Arts', 'Food', 'Quirky'],
  },
  {
    id: 'chicago',
    name: 'Chicago',
    state: 'IL',
    driveHours: 2.5,
    anchor: 'Art Institute & Millennium Park',
    description: 'The full metropolis hit — world-class art, deep-dish pizza, lake views that feel bigger than they should.',
    vibes: ['Arts', 'Food', 'History'],
  },
  {
    id: 'louisville',
    name: 'Louisville',
    state: 'KY',
    driveHours: 2.5,
    anchor: 'Churchill Downs & Bourbon Row',
    description: 'Horses, bourbon barrels, and a food scene that became a genuine destination without trying to.',
    vibes: ['History', 'Food', 'Quirky'],
  },
  {
    id: 'put-in-bay',
    name: 'Put-in-Bay',
    state: 'OH',
    driveHours: 3,
    anchor: "Perry's Victory Monument",
    description: 'A Lake Erie island reached by ferry, with a 352-foot granite column, golf carts for rent, and zero agenda.',
    vibes: ['Nature', 'History', 'Quirky'],
  },
  {
    id: 'cleveland',
    name: 'Cleveland',
    state: 'OH',
    driveHours: 3,
    anchor: 'Rock & Roll Hall of Fame',
    description: 'Underrated in the best way — a waterfront city with a chip on its shoulder and a lot of surprises.',
    vibes: ['History', 'Arts', 'Music'],
  },
  {
    id: 'galena',
    name: 'Galena',
    state: 'IL',
    driveHours: 3.5,
    anchor: "Ulysses S. Grant's Hometown",
    description: "A perfectly preserved 1800s Main Street, antique shops that actually have good stuff, and rolling Illinois countryside.",
    vibes: ['History', 'Quirky', 'Arts'],
  },
  {
    id: 'sleeping-bear-dunes',
    name: 'Sleeping Bear Dunes',
    state: 'MI',
    driveHours: 3.5,
    anchor: '450-Ft Sand Dunes over Lake Michigan',
    description: 'You climb a sand mountain, your legs give out, and the reward is a view of Lake Michigan that looks like the ocean.',
    vibes: ['Nature', 'Quirky'],
  },
  {
    id: 'mackinac-island',
    name: 'Mackinac Island',
    state: 'MI',
    driveHours: 4.5,
    anchor: 'A Car-Free Island Frozen in 1898',
    description: 'No cars allowed. Arrive by ferry, get around by horse or bike, and eat more fudge than you planned to.',
    vibes: ['Nature', 'History', 'Quirky', 'Food'],
  },
  {
    id: 'nashville',
    name: 'Nashville',
    state: 'TN',
    driveHours: 5,
    anchor: 'Honky-Tonk Row on Broadway',
    description: 'Live music spilling out of every door, hot chicken that earns its reputation, and a city that never really sleeps.',
    vibes: ['Music', 'Food', 'Arts'],
  },
];
