const DESTINATIONS = [
  {
    id: 'indianapolis',
    name: 'Indianapolis',
    state: 'IN',
    driveHours: 1.5,
    drive_minutes: 90,
    drive_from_fort_wayne: '1.5 hrs',
    hook: 'Racing history, a revived downtown, and some of the best food in the Midwest — all without the big-city chaos.',
    anchor_name: 'Indianapolis Motor Speedway',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Arts', 'Food'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Indianapolis-1872529_1920_%28cropped%29.jpg/960px-Indianapolis-1872529_1920_%28cropped%29.jpg',
  },
  {
    id: 'crawfordsville-in',
    name: 'Crawfordsville',
    state: 'IN',
    driveHours: 1.5,
    drive_minutes: 90,
    drive_from_fort_wayne: '1.5 hrs',
    hook: 'Home to the only working rotary jail in the world — a 32-ton hand-cranked cell block that spins. Pair it with a tiny house stay and a walkable small-town downtown that punches well above its size.',
    anchor_name: 'Rotary Jail Museum',
    anchor_description: 'Built in 1882, this is the last fully operational rotary jail on earth — one door, spinning cells, and stories of prisoners who lost limbs when the mechanism jammed.',
    anchor_address: '225 N Washington St, Crawfordsville, IN 47933',
    anchor_hours: 'Wed–Sat 10am–3pm (spring/fall) or 10am–5pm (summer). Closed Jan–Feb.',
    anchor_cost: '$8 adults / $5 kids 6–11 / free under 5',
    tags: ['History', 'Quirky'],
    vibe: 'Welcoming and laid-back. Locals are friendly, pace is slow. Feels like a town that knows it has something special and wants to share it.',
    best_season: 'Spring, Summer, Fall',
    estimated_cost_low: 80,
    estimated_cost_high: 150,
    where_to_stay: 'Search VRBO for tiny houses near Crawfordsville — there are genuinely cool options within a few miles. Worth spending 20 minutes finding something unique instead of defaulting to a chain hotel.',
    food_picks: [
      'Francis & Mount — top-rated downtown spot, good for dinner',
      'El Charro — authentic Mexican, local favorite, lively atmosphere',
      'The Joshua Cup — downtown coffee shop, great for a slow morning start',
    ],
    other_stops: [
      'General Lew Wallace Study & Museum — the Ben-Hur author lived here, stunning building',
      'Downtown antique shops — easy to kill an hour or two',
      'Carnegie Museum of Montgomery County',
    ],
    suggested_order: 'Arrive Friday evening, settle into your stay. Saturday morning: coffee at The Joshua Cup, then Rotary Jail (opens 10am). Afternoon: antiques and downtown exploring. Dinner at Francis & Mount or El Charro. Sunday: General Lew Wallace museum before heading home.',
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Crawfordsville%2C+Indiana',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Rotary_Jail_Museum_%2814609994818%29.jpg/960px-Rotary_Jail_Museum_%2814609994818%29.jpg',
  },
  {
    id: 'cincinnati',
    name: 'Cincinnati',
    state: 'OH',
    driveHours: 2,
    drive_minutes: 120,
    drive_from_fort_wayne: '2 hrs',
    hook: 'Victorian row houses, craft breweries on every block, and Cincinnati chili — a city with a personality all its own.',
    anchor_name: 'Over-the-Rhine Historic District',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Arts', 'Food'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Downtown_Cincinnati_viewed_from_Devou_Park_%28cropped%29.jpg/960px-Downtown_Cincinnati_viewed_from_Devou_Park_%28cropped%29.jpg',
  },
  {
    id: 'detroit',
    name: 'Detroit',
    state: 'MI',
    driveHours: 2,
    drive_minutes: 120,
    drive_from_fort_wayne: '2 hrs',
    hook: "One of America's great comeback stories, with art, music, and food that punch well above their weight.",
    anchor_name: 'Motown Museum',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Arts', 'Music', 'Food'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Detroit_Skyline_from_Windsor_2025-09-01.jpg/960px-Detroit_Skyline_from_Windsor_2025-09-01.jpg',
  },
  {
    id: 'columbus',
    name: 'Columbus',
    state: 'OH',
    driveHours: 2.5,
    drive_minutes: 150,
    drive_from_fort_wayne: '2.5 hrs',
    hook: 'A walkable arts corridor, James Beard–worthy restaurants, and a college city that got unexpectedly cool.',
    anchor_name: 'Short North Arts District',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Arts', 'Food', 'Quirky'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Downtown_Columbus_View_from_Main_St_Bridge_-_edit1.jpg/960px-Downtown_Columbus_View_from_Main_St_Bridge_-_edit1.jpg',
  },
  {
    id: 'chicago',
    name: 'Chicago',
    state: 'IL',
    driveHours: 2.5,
    drive_minutes: 150,
    drive_from_fort_wayne: '2.5 hrs',
    hook: 'The full metropolis hit — world-class art, deep-dish pizza, lake views that feel bigger than they should.',
    anchor_name: 'Art Institute & Millennium Park',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Arts', 'Food', 'History'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Chicago_River_ferry_b.jpg/960px-Chicago_River_ferry_b.jpg',
  },
  {
    id: 'louisville',
    name: 'Louisville',
    state: 'KY',
    driveHours: 2.5,
    drive_minutes: 150,
    drive_from_fort_wayne: '2.5 hrs',
    hook: 'Horses, bourbon barrels, and a food scene that became a genuine destination without trying to.',
    anchor_name: 'Churchill Downs & Bourbon Row',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Food', 'Quirky'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Louisville_Skyline_2021_%283%29.jpg/960px-Louisville_Skyline_2021_%283%29.jpg',
  },
  {
    id: 'put-in-bay',
    name: 'Put-in-Bay',
    state: 'OH',
    driveHours: 3,
    drive_minutes: 180,
    drive_from_fort_wayne: '3 hrs',
    hook: 'A Lake Erie island reached by ferry, with a 352-foot granite column, golf carts for rent, and zero agenda.',
    anchor_name: "Perry's Victory Monument",
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Nature', 'History', 'Quirky', 'Water'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Perry%27s_Victory_and_International_Peace_Memorial_%284663688070%29.jpg/960px-Perry%27s_Victory_and_International_Peace_Memorial_%284663688070%29.jpg',
  },
  {
    id: 'cleveland',
    name: 'Cleveland',
    state: 'OH',
    driveHours: 3,
    drive_minutes: 180,
    drive_from_fort_wayne: '3 hrs',
    hook: 'Underrated in the best way — a waterfront city with a chip on its shoulder and a lot of surprises.',
    anchor_name: 'Rock & Roll Hall of Fame',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Arts', 'Music'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Cleveland_skyline_from_Lakewood_Park%2C_January_2026.jpg/960px-Cleveland_skyline_from_Lakewood_Park%2C_January_2026.jpg',
  },
  {
    id: 'galena',
    name: 'Galena',
    state: 'IL',
    driveHours: 3.5,
    drive_minutes: 210,
    drive_from_fort_wayne: '3.5 hrs',
    hook: "A perfectly preserved 1800s Main Street, antique shops that actually have good stuff, and rolling Illinois countryside.",
    anchor_name: "Ulysses S. Grant's Hometown",
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Quirky', 'Arts'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Galena%2C_Illinois.jpg/960px-Galena%2C_Illinois.jpg',
  },
  {
    id: 'sleeping-bear-dunes',
    name: 'Sleeping Bear Dunes',
    state: 'MI',
    driveHours: 3.5,
    drive_minutes: 210,
    drive_from_fort_wayne: '3.5 hrs',
    hook: 'You climb a sand mountain, your legs give out, and the reward is a view of Lake Michigan that looks like the ocean.',
    anchor_name: '450-Ft Sand Dunes over Lake Michigan',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Nature', 'Quirky', 'Water'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Dunes_and_fog_from_Platte_Point_%2895c5ad13-5f8a-4a59-838f-50b9a644648c%29.jpg/960px-Dunes_and_fog_from_Platte_Point_%2895c5ad13-5f8a-4a59-838f-50b9a644648c%29.jpg',
  },
  {
    id: 'mackinac-island',
    name: 'Mackinac Island',
    state: 'MI',
    driveHours: 4.5,
    drive_minutes: 270,
    drive_from_fort_wayne: '4.5 hrs',
    hook: 'No cars allowed. Arrive by ferry, get around by horse or bike, and eat more fudge than you planned to.',
    anchor_name: 'A Car-Free Island Frozen in 1898',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Nature', 'History', 'Quirky', 'Food', 'Water'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Mackinac_Island%27s_main_town%2C_looking_west._Transportation_on_the_island_is_by_horse%2C_bike%2C_or_foot..jpg/960px-Mackinac_Island%27s_main_town%2C_looking_west._Transportation_on_the_island_is_by_horse%2C_bike%2C_or_foot..jpg',
  },
  {
    id: 'nashville',
    name: 'Nashville',
    state: 'TN',
    driveHours: 5,
    drive_minutes: 300,
    drive_from_fort_wayne: '5 hrs',
    hook: 'Live music spilling out of every door, hot chicken that earns its reputation, and a city that never really sleeps.',
    anchor_name: 'Honky-Tonk Row on Broadway',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Music', 'Food', 'Arts'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nashville%2C_TN_skyline.jpg/960px-Nashville%2C_TN_skyline.jpg',
  },
];
