const DESTINATIONS = [
  {
    id: 'shipshewana',
    name: 'Shipshewana',
    state: 'IN',
    driveHours: 0.75,
    drive_minutes: 45,
    drive_from_fort_wayne: '45 min',
    hook: "The largest outdoor flea market in the Midwest, surrounded by working Amish farms and buggies sharing the road. It's 45 minutes from Fort Wayne and a genuine glimpse into a completely different pace of life.",
    anchor_name: 'Shipshewana Flea Market',
    anchor_description: 'Over 700 vendors spread across 100 acres every Tuesday and Wednesday, May through October. Antiques, furniture, produce, livestock — the real thing, not a curated artisan market.',
    anchor_address: '345 S Van Buren St, Shipshewana, IN 46565',
    anchor_hours: 'Tues & Wed 8am–5pm, May–October; limited dates in April and November',
    anchor_cost: 'Free admission; vendor prices vary',
    tags: ['History', 'Quirky', 'Food'],
    vibe: "Unhurried and genuinely different. You're a guest in someone else's way of life — respect it and you'll get a lot back. Locals are generous if you're curious rather than gawking. Pace your expectations accordingly.",
    best_season: 'Spring, Summer, Fall',
    estimated_cost_low: 60,
    estimated_cost_high: 120,
    where_to_stay: 'Farmstead Inn in Shipshewana is the obvious choice — quirky but solid. Or treat it as a day trip; 45 minutes is close enough to not need a hotel.',
    food_picks: [
      "Blue Gate Restaurant — Amish family-style meals, massive portions, worth the wait. Get the chicken and noodles.",
      "Yoder's Meat & Cheese — deli counter loaded with local specialties, good for loading up before the drive home",
      "Das Dutchman Essenhaus (Middlebury, 15 min away) — same energy as Blue Gate, even bigger, better for groups",
    ],
    other_stops: [
      'Menno-Hof — Mennonite/Amish interpretive center, thoughtful and not kitschy, worth an hour',
      'Deutsch Kase Haus cheese factory in Middlebury — free samples, small operation you can watch',
      'Downtown antique shops along SR 5 — easy to lose an afternoon',
    ],
    suggested_order: "Leave Fort Wayne by 8am on a Tuesday or Wednesday to catch the flea market opening. Wander for 2-3 hours before the midday crowd. Lunch at Blue Gate (expect a wait — put your name in early). Afternoon at Menno-Hof, then poke around the shops. Back home by late afternoon.",
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Shipshewana%2C+Indiana',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Jrb_20071024_Mennonite_Amish_buggy_Shipshewana_Indiana.JPG/960px-Jrb_20071024_Mennonite_Amish_buggy_Shipshewana_Indiana.JPG',
  },
  {
    id: 'portland-in',
    name: 'Portland',
    state: 'IN',
    driveHours: 1,
    drive_minutes: 60,
    drive_from_fort_wayne: '1 hr',
    hook: "Deep rural northeast Indiana — a county seat square, the Gene Stratton-Porter Limberlost country nearby, and the kind of unhurried Saturday morning that's hard to find close to home.",
    anchor_name: "Gene Stratton-Porter's Limberlost Cabin",
    anchor_description: "The naturalist who wrote Freckles and A Girl of the Limberlost lived in this log cabin from 1895 to 1913, studying the vanishing wetlands around her. The cabin and grounds are a state historic site.",
    anchor_address: '200 E 6th St, Geneva, IN 46740',
    anchor_hours: 'Wed–Sat 9am–5pm, Sun 1–5pm; closed Jan–Feb',
    anchor_cost: '$5 adults / $3 youth 5–11',
    tags: ['Nature', 'History', 'Quirky'],
    vibe: "Genuinely quiet, genuinely small-town Indiana. No tourist infrastructure means you experience the real thing. The Jay County Courthouse square is the kind of place where people still sit on benches and say hello.",
    best_season: 'Spring, Summer, Fall',
    estimated_cost_low: 40,
    estimated_cost_high: 80,
    where_to_stay: 'Best as a day trip — the drive is short enough to make it an easy out-and-back.',
    food_picks: [
      'Country Kitchen — solid home-cooking diner on the square, no surprises in the best way',
      'Branding Iron — casual steakhouse and local watering hole',
      'Coney Island Dairy Bar — seasonal soft serve, the kind of stop that makes the day',
    ],
    other_stops: [
      'Jay County Courthouse — 1919 neoclassical building anchoring a walkable downtown square',
      'Loblolly Marsh Wetland Preserve — easy nature walk, good birding in spring',
      'Portland riverfront — quiet Salamonie River greenway, good for a short walk',
    ],
    suggested_order: "Leave early, hit the Limberlost Cabin when it opens (Geneva is 20 min south of Portland). Spend an hour there. Drive up to Portland for lunch on the square. Walk the courthouse grounds and browse the downtown. Loblolly Marsh on the way back if the weather's nice.",
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Portland%2C+Indiana',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Jay_County_Courthouse_P4020129.jpg/960px-Jay_County_Courthouse_P4020129.jpg',
  },
  {
    id: 'toledo',
    name: 'Toledo',
    state: 'OH',
    driveHours: 1,
    drive_minutes: 60,
    drive_from_fort_wayne: '1 hr',
    hook: "The Toledo Museum of Art charges nothing and holds one of the finest glass collections on earth. Add a Mud Hens game, the best Tony Packo's hot dog you'll ever eat, and a riverfront mid-comeback — it outperforms most bigger cities for a day trip.",
    anchor_name: 'Toledo Museum of Art',
    anchor_description: "Free admission always. The Glass Pavilion is a 76,000 sq ft glass building housing thousands of glass objects — the museum was glass-obsessed before Toledo glass manufacturing put the city on the map.",
    anchor_address: '2445 Monroe St, Toledo, OH 43620',
    anchor_hours: 'Wed & Fri–Sun 10am–4pm, Thu 10am–8pm; closed Mon & Tue',
    anchor_cost: 'Free',
    tags: ['Arts', 'History', 'Food'],
    vibe: 'A Great Lakes city in the middle of reinventing itself. Less polished than Cleveland or Cincinnati, which means cheaper food and no lines anywhere. Glass City pride runs deep — locals will tell you about the museum unprompted.',
    best_season: 'Year-round',
    estimated_cost_low: 40,
    estimated_cost_high: 100,
    where_to_stay: 'Day trip from Fort Wayne. If staying overnight: Hampton Inn downtown or the Courtyard Maumee for better rates.',
    food_picks: [
      "Tony Packo's — Hungarian hot dogs that Anthony Bourdain reviewed and Corporal Klinger name-dropped on M*A*S*H for 11 seasons. Original on Front Street.",
      "Mancy's Steaks — Toledo institution since 1921, worth splurging on for dinner",
      "Cosi Cucina — Italian on the Maumee River, locally loved, solid for a long lunch",
    ],
    other_stops: [
      "Toledo Zoo — consistently ranked one of the best in the country, genuinely impressive if you're going with kids",
      'Fifth Third Field — catch a Mud Hens game (AAA baseball, cheap tickets, fun atmosphere)',
      'International Park on the Maumee River — good walk after the museum',
      'Brim and Crown — best cocktail bar in the Warehouse District',
    ],
    suggested_order: "Museum opens at 10am — get there right at opening. Plan 2-3 hours minimum (Glass Pavilion alone is worth the drive). Lunch at Tony Packo's on Front Street. Afternoon: riverfront walk or the Toledo Zoo if you have more time. Head home by early evening.",
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Toledo%2C+Ohio',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Toledo_Museum_of_Art_exterior%2C_Art_Museum_Dr_entrance.jpg/960px-Toledo_Museum_of_Art_exterior%2C_Art_Museum_Dr_entrance.jpg',
  },
  {
    id: 'indianapolis',
    name: 'Indianapolis',
    state: 'IN',
    driveHours: 1.5,
    drive_minutes: 90,
    drive_from_fort_wayne: '1.5 hrs',
    hook: 'Racing history, a revived downtown, and some of the best food in the Midwest — all without the big-city chaos.',
    anchor_name: 'Indianapolis Motor Speedway',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Arts', 'Food'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Indianapolis-1872529_1920_%28cropped%29.jpg/960px-Indianapolis-1872529_1920_%28cropped%29.jpg',
  },
  {
    id: 'crawfordsville-in',
    name: 'Crawfordsville',
    state: 'IN',
    driveHours: 1.5,
    drive_minutes: 90,
    drive_from_fort_wayne: '1.5 hrs',
    hook: 'Home to the only working rotary jail in the world — a 32-ton hand-cranked cell block that spins. Pair it with a tiny house stay and a walkable small-town downtown that punches well above its size.',
    anchor_name: 'Rotary Jail Museum',
    anchor_description: 'Built in 1882, this is the last fully operational rotary jail on earth — one door, spinning cells, and stories of prisoners who lost limbs when the mechanism jammed.',
    anchor_address: '225 N Washington St, Crawfordsville, IN 47933',
    anchor_hours: 'Wed–Sat 10am–3pm (spring/fall) or 10am–5pm (summer). Closed Jan–Feb.',
    anchor_cost: '$8 adults / $5 kids 6–11 / free under 5',
    tags: ['History', 'Quirky'],
    vibe: 'Welcoming and laid-back. Locals are friendly, pace is slow. Feels like a town that knows it has something special and wants to share it.',
    best_season: 'Spring, Summer, Fall',
    estimated_cost_low: 80,
    estimated_cost_high: 150,
    where_to_stay: 'Search VRBO for tiny houses near Crawfordsville — there are genuinely cool options within a few miles. Worth spending 20 minutes finding something unique instead of defaulting to a chain hotel.',
    food_picks: [
      'Francis & Mount — top-rated downtown spot, good for dinner',
      'El Charro — authentic Mexican, local favorite, lively atmosphere',
      'The Joshua Cup — downtown coffee shop, great for a slow morning start',
    ],
    other_stops: [
      'General Lew Wallace Study & Museum — the Ben-Hur author lived here, stunning building',
      'Downtown antique shops — easy to kill an hour or two',
      'Carnegie Museum of Montgomery County',
    ],
    suggested_order: 'Arrive Friday evening, settle into your stay. Saturday morning: coffee at The Joshua Cup, then Rotary Jail (opens 10am). Afternoon: antiques and downtown exploring. Dinner at Francis & Mount or El Charro. Sunday: General Lew Wallace museum before heading home.',
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Crawfordsville%2C+Indiana',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Rotary_Jail_Museum_%2814609994818%29.jpg/960px-Rotary_Jail_Museum_%2814609994818%29.jpg',
  },
  {
    id: 'williamsport-in',
    name: 'Williamsport',
    state: 'IN',
    driveHours: 1.5,
    drive_minutes: 90,
    drive_from_fort_wayne: '1.5 hrs',
    hook: "Indiana's tallest waterfall — a 90-foot drop tucked behind a small county-seat park — is the kind of thing you'd expect to drive to a national park for. It's 90 minutes away.",
    anchor_name: 'Williamsport Falls',
    anchor_description: 'The highest waterfall in Indiana, a free-falling 90-foot cascade on Fall Fork Creek. Best in spring when the water runs full. A short path from the parking area.',
    anchor_address: 'Falls Park, Williamsport, IN 47993',
    anchor_hours: 'Open year-round, dawn to dusk',
    anchor_cost: 'Free',
    tags: ['Nature', 'Quirky'],
    vibe: "Nobody's putting this on Instagram yet. A classic small Indiana county seat with a genuinely surprising natural feature at its edge. Quiet enough that you'll probably have the falls to yourself on a weekday.",
    best_season: 'Spring (highest water volume), Fall',
    estimated_cost_low: 30,
    estimated_cost_high: 70,
    where_to_stay: 'Best as a day trip. Combine with Portland Arch Nature Preserve or Turkey Run to fill a full day.',
    food_picks: [
      "There's a small-town diner atmosphere on the square — ask a local what's open",
      'Bring a picnic for the falls — honestly the best option',
      'Combine with a stop at Back Roads Brewing in nearby Rockville on the way home',
    ],
    other_stops: [
      'Warren County Courthouse — 1908 Beaux-Arts building anchoring a quiet downtown square',
      'Portland Arch Nature Preserve — 25 min south near Fountain, natural sandstone arch and good trails',
      'Williamsport square — small, unhurried, worth a walk',
    ],
    suggested_order: 'Drive out in the morning. Falls first — 15-minute walk from parking, more dramatic than you expect. Walk the downtown square and find coffee or lunch. Portland Arch if you want more trails. Back home by dinner.',
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Williamsport%2C+Indiana',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Williamsport_Falls_1.jpg/960px-Williamsport_Falls_1.jpg',
  },
  {
    id: 'cincinnati',
    name: 'Cincinnati',
    state: 'OH',
    driveHours: 2,
    drive_minutes: 120,
    drive_from_fort_wayne: '2 hrs',
    hook: 'Victorian row houses, craft breweries on every block, and Cincinnati chili — a city with a personality all its own.',
    anchor_name: 'Over-the-Rhine Historic District',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Arts', 'Food'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Downtown_Cincinnati_viewed_from_Devou_Park_%28cropped%29.jpg/960px-Downtown_Cincinnati_viewed_from_Devou_Park_%28cropped%29.jpg',
  },
  {
    id: 'detroit',
    name: 'Detroit',
    state: 'MI',
    driveHours: 2,
    drive_minutes: 120,
    drive_from_fort_wayne: '2 hrs',
    hook: "One of America's great comeback stories, with art, music, and food that punch well above their weight.",
    anchor_name: 'Motown Museum',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Arts', 'Music', 'Food'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Detroit_Skyline_from_Windsor_2025-09-01.jpg/960px-Detroit_Skyline_from_Windsor_2025-09-01.jpg',
  },
  {
    id: 'turkey-run',
    name: 'Turkey Run State Park',
    state: 'IN',
    driveHours: 2,
    drive_minutes: 120,
    drive_from_fort_wayne: '2 hrs',
    hook: "Sandstone canyons and ladder trails that drop into rocky hollows that don't look like Indiana. This is the park people drive past on the way to Nashville and regret not stopping.",
    anchor_name: 'Rocky Hollow – Fall Creek Trail System',
    anchor_description: "Trail 3 runs through a slot canyon carved by Sugar Creek — you climb ladders, ford streams, and scramble through passages that feel more like the American West than the Midwest.",
    anchor_address: '8121 Park Rd, Marshall, IN 47859',
    anchor_hours: 'Park open year-round; Turkey Run Inn on-site for lodging',
    anchor_cost: '$7/vehicle IN residents; $9 out-of-state',
    tags: ['Nature', 'Quirky'],
    vibe: "An Indiana state park classic — families, serious hikers, and people who grew up coming here. Genuinely beautiful terrain that surprises first-timers every time. The inn makes it easy to stay the weekend.",
    best_season: 'Spring (wildflowers), Fall (peak color)',
    estimated_cost_low: 60,
    estimated_cost_high: 160,
    where_to_stay: "Turkey Run Inn — on-site lodge, affordable and genuinely atmospheric. Book ahead for weekends in fall. Cabins available too.",
    food_picks: [
      "Turkey Run Inn dining room — reliable, convenient, and you're already there",
      "Milligan's Dairy Bar in Rockville — soft serve institution, 15 min from the park",
      "Back Roads Brewing in Rockville — local craft beer, good stop after the trails",
    ],
    other_stops: [
      'Narrows Covered Bridge — historic covered bridge on Sugar Creek, 10 min from the park',
      'Shades State Park — 20 min away, even more dramatic sandstone terrain with fewer visitors',
      'Downtown Rockville — county seat with antiques, a nice square, and a slower pace',
    ],
    suggested_order: 'Arrive Friday evening, check into Turkey Run Inn. Saturday: hit Trail 3 (Rocky Hollow) early before the crowds — expect to get your feet wet. Lunch at the inn. Afternoon: Trail 10 or drive to Shades. Evening: Milligan\'s Dairy Bar, dinner at the inn. Sunday: Narrows Bridge, Rockville antiques, then home.',
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Turkey+Run+State+Park%2C+Indiana',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Sugar_Creek_Turkey_Run_SP%2C_IN_2.jpg/960px-Sugar_Creek_Turkey_Run_SP%2C_IN_2.jpg',
  },
  {
    id: 'yellow-springs',
    name: 'Yellow Springs',
    state: 'OH',
    driveHours: 2,
    drive_minutes: 120,
    drive_from_fort_wayne: '2 hrs',
    hook: "Dave Chappelle moved here for the quiet. The town is everything a small arts community should be — independent bookshops, a good record store, real hiking right off Main Street, and restaurants that actually try.",
    anchor_name: 'Glen Helen Nature Preserve',
    anchor_description: "A 1,000-acre nature preserve owned by Antioch College, with trails through old-growth forest, a yellow sulphur spring (the town's namesake), and the kind of quiet that's hard to find two hours from anywhere.",
    anchor_address: '405 Corry St, Yellow Springs, OH 45387',
    anchor_hours: 'Open daily dawn–dusk',
    anchor_cost: 'Free (donations welcome)',
    tags: ['Nature', 'Arts', 'Quirky', 'Food'],
    vibe: 'Relaxed, progressive, unhurried. Antioch College has kept it weird for over 150 years. Indie shops, good food, real hiking — and nobody cares who you are or what you look like. Genuinely one of the nicest small towns in Ohio.',
    best_season: 'Spring, Summer, Fall',
    estimated_cost_low: 60,
    estimated_cost_high: 130,
    where_to_stay: 'The Antioch Inn or Airbnbs in town — Yellow Springs is small enough that anything walkable to Main Street works. Book ahead in spring; it fills up.',
    food_picks: [
      'Sunrise Cafe — the breakfast spot, always crowded for good reason. Put your name in before you explore.',
      "Peach's Grill — local favorite, unpretentious and consistently good",
      "Young's Jersey Dairy — farm and ice cream shop outside of town. A required stop. The drive-through ice cream is better than it sounds.",
    ],
    other_stops: [
      'Antioch College campus — walk the grounds, interesting architecture and an unusual history',
      'The Spirited Goat Coffee House — best place to sit, read, and watch Main Street',
      'Emporium Wine — well-curated natural wine selection, good for picking up a bottle',
      'Dark Star Books & Comics — independent bookstore with genuine depth',
    ],
    suggested_order: 'Saturday morning: Sunrise Cafe for breakfast (expect a wait — worth it). Glen Helen for 2-3 hours on the trails. Lunch in town. Afternoon: browse the shops, Emporium Wine, the record store. Sunday: Young\'s Jersey Dairy on the way out — it\'s a full farm with a walk-up ice cream window and it will not disappoint.',
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Yellow+Springs%2C+Ohio',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Yellow_Springs_Station.jpg/960px-Yellow_Springs_Station.jpg',
  },
  {
    id: 'columbus-in',
    name: 'Columbus',
    state: 'IN',
    driveHours: 2,
    drive_minutes: 120,
    drive_from_fort_wayne: '2 hrs',
    hook: "A city of 50,000 in south-central Indiana with more Pritzker Prize architecture per capita than almost anywhere on earth. Eero Saarinen, I.M. Pei, Richard Meier — all here, because Cummins Engine paid for it.",
    anchor_name: 'Columbus Architecture Tour',
    anchor_description: "The Cummins Foundation has been funding world-class buildings in Columbus since 1954 — paying design fees for every public building if the city chose from a list of approved architects. The result is a small Midwestern city where the fire station, the library, and the post office are masterpieces.",
    anchor_address: '506 5th St, Columbus, IN 47201 (Visitor Center)',
    anchor_hours: 'Mon–Sat 9am–5pm, Sun 10am–4pm; bus tours available Sat–Sun',
    anchor_cost: 'Self-guided walking tour free; bus tours $25–30/person',
    tags: ['Arts', 'History', 'Quirky'],
    vibe: "Calm and unexpectedly sophisticated. Locals are quietly proud — they grew up around masterpieces and know it's unusual. The architecture isn't staged for tourists; it's just the fire station, the library, the school.",
    best_season: 'Year-round',
    estimated_cost_low: 60,
    estimated_cost_high: 140,
    where_to_stay: "The Inn at Irwin Gardens — a 1910 Italian Renaissance estate, the most interesting option in town. Standard hotels downtown also available.",
    food_picks: [
      "Zaharako's Ice Cream Parlor — operating soda fountain since 1900, same marble counters and pipe organ. A genuine artifact.",
      'Henry Social Club — the best dinner in town, James Beard territory, worth making a reservation',
      'Commons Café — casual downtown lunch option inside the architecturally significant Commons mall',
    ],
    other_stops: [
      "Miller House and Garden — Eero Saarinen / Alexander Girard masterpiece, requires advance tickets through the IMA. The interior is like stepping into a design museum that people actually lived in.",
      'First Christian Church — Eliel Saarinen design, 1942, stunning interior open for self-guided visits',
      'Bartholomew County Public Library — I.M. Pei, open to browse and use',
      "Columbus City Hall — Kevin Roche, 1981, striking exterior in the downtown core",
    ],
    suggested_order: "Pick up the free walking tour map at the Visitor Center first — it routes you efficiently through 70+ buildings. Spend the morning walking key structures. Lunch at Zaharako's. Afternoon: Miller House tour if you reserved ahead (strongly recommended, limited slots). More buildings after. This fills a full day without trying.",
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Columbus%2C+Indiana',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Stewart-bridge-1933328.jpg/960px-Stewart-bridge-1933328.jpg',
  },
  {
    id: 'columbus',
    name: 'Columbus',
    state: 'OH',
    driveHours: 2.5,
    drive_minutes: 150,
    drive_from_fort_wayne: '2.5 hrs',
    hook: 'A walkable arts corridor, James Beard–worthy restaurants, and a college city that got unexpectedly cool.',
    anchor_name: 'Short North Arts District',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Arts', 'Food', 'Quirky'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Downtown_Columbus_View_from_Main_St_Bridge_-_edit1.jpg/960px-Downtown_Columbus_View_from_Main_St_Bridge_-_edit1.jpg',
  },
  {
    id: 'chicago',
    name: 'Chicago',
    state: 'IL',
    driveHours: 2.5,
    drive_minutes: 150,
    drive_from_fort_wayne: '2.5 hrs',
    hook: 'The full metropolis hit — world-class art, deep-dish pizza, lake views that feel bigger than they should.',
    anchor_name: 'Art Institute & Millennium Park',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Arts', 'Food', 'History'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Chicago_River_ferry_b.jpg/960px-Chicago_River_ferry_b.jpg',
  },
  {
    id: 'louisville',
    name: 'Louisville',
    state: 'KY',
    driveHours: 2.5,
    drive_minutes: 150,
    drive_from_fort_wayne: '2.5 hrs',
    hook: 'Horses, bourbon barrels, and a food scene that became a genuine destination without trying to.',
    anchor_name: 'Churchill Downs & Bourbon Row',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Food', 'Quirky'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Louisville_Skyline_2021_%283%29.jpg/960px-Louisville_Skyline_2021_%283%29.jpg',
  },
  {
    id: 'frankenmuth',
    name: 'Frankenmuth',
    state: 'MI',
    driveHours: 2.5,
    drive_minutes: 150,
    drive_from_fort_wayne: '2.5 hrs',
    hook: "The world's largest Christmas store is open 361 days a year in a town that smells like chicken dinner. It's unabashedly over-the-top, it works on you anyway, and the chicken genuinely is that good.",
    anchor_name: "Bronner's Christmas Wonderland",
    anchor_description: "260 decorated trees, 100,000 ornaments, and a building larger than five football fields. Open almost every day of the year. The scale is genuinely hard to process until you're inside.",
    anchor_address: '25 Christmas Ln, Frankenmuth, MI 48734',
    anchor_hours: 'Mon–Sat 9am–8pm (extended December hours); closed Thanksgiving, Christmas Day, New Year\'s Day, Easter',
    anchor_cost: 'Free admission',
    tags: ['History', 'Food', 'Quirky'],
    vibe: "Cheerful and a little surreal. It's a Bavarian village in Michigan that takes itself completely seriously — and that commitment is the whole charm. Best in December but honestly fun any time of year.",
    best_season: 'December (peak), Summer (busy with families), Fall',
    estimated_cost_low: 80,
    estimated_cost_high: 180,
    where_to_stay: "Bavarian Inn Lodge — on-site hotel attached to the restaurant, indoor water park, the full Frankenmuth experience. Zehnder's Bavarian Haus also available across the street.",
    food_picks: [
      "Zehnder's of Frankenmuth — all-you-can-eat chicken dinner since 1928. One of the largest restaurants in the country by seating. The chicken is the reason you came.",
      'Bavarian Inn Restaurant — same deal across the street, rival institution since the 1960s. Arguments about which is better run deep locally.',
      "Frankenmuth Brewery — Michigan's oldest brewery (founded 1862), solid German-style lager and pilsner in a historic building",
    ],
    other_stops: [
      'St. Lorenz Lutheran Church — the original Frankenmuth church, worth a look for the history',
      'Frankenmuth Cheese Haus — obvious but fun, good for loading up before the drive home',
      'River Place Shops along the Cass River — touristy browsing, good for an afternoon',
    ],
    suggested_order: 'Arrive Saturday morning. Chicken dinner at either Zehnder\'s or Bavarian Inn — lines start building by noon, so go early or late. Afternoon at Bronner\'s — budget 2-3 hours, it\'s massive. Frankenmuth Brewery in the evening. Sunday: browse the cheese shops and Riverplatz Walk before heading home.',
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Frankenmuth%2C+Michigan',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Main_Street%2C_Frankenmuth%2C_Michigan%2C_2014-01-11.jpg/960px-Main_Street%2C_Frankenmuth%2C_Michigan%2C_2014-01-11.jpg',
  },
  {
    id: 'coshocton',
    name: 'Coshocton',
    state: 'OH',
    driveHours: 2.5,
    drive_minutes: 150,
    drive_from_fort_wayne: '2.5 hrs',
    hook: "An 1830s Ohio canal town that got restored instead of demolished. Horse-drawn canal boat rides, a working living-history village, and a pace that makes it feel like the weekend actually slowed down.",
    anchor_name: 'Roscoe Village',
    anchor_description: "A restored 1830s canal town along the Ohio & Erie Canal. Costumed interpreters, a working canal boat, period craft shops, and buildings that were abandoned for a century before anyone thought to save them.",
    anchor_address: '381 Hill St, Coshocton, OH 43812',
    anchor_hours: 'Village grounds open daily; shops and canal boat typically 10am–5pm spring through fall',
    anchor_cost: 'Free to walk; canal boat ride $8–12/person (seasonal)',
    tags: ['History', 'Quirky'],
    vibe: "Quiet, genuinely historic, slightly time-warped in a good way. Not overwhelmed by tourists. The restoration is real and careful, not theme-park. Good for people who like history without the crowds or the bus tour.",
    best_season: 'Spring, Summer, Fall (canal boat runs seasonally)',
    estimated_cost_low: 60,
    estimated_cost_high: 130,
    where_to_stay: 'Roscoe Village Inn — right in the historic district, the obvious choice. Affordable and atmospheric.',
    food_picks: [
      "Warehouse Steak 'n Stein — Roscoe Village's main restaurant, good beef and a local-bar atmosphere",
      'Coshocton Brewing Company — solid local brewery right in the village area, best option for a relaxed evening',
      "Old Warehouse Restaurant — casual, reliable, has been feeding people here for decades",
    ],
    other_stops: [
      'Ohio & Erie Canal Visitor Center — good orientation for the history before you walk the village',
      'Johnson-Humrickhouse Museum — eclectic collection with Native American artifacts and period household objects',
      'Clary Gardens — 7 acres of botanical gardens, quiet and good for an afternoon walk',
    ],
    suggested_order: 'Check in Friday evening. Saturday: canal boat ride first thing (check the schedule online, it fills up). Village walking tour mid-morning. Lunch at Coshocton Brewing Company. Afternoon: Johnson-Humrickhouse Museum, Clary Gardens. Dinner at Warehouse Steak \'n Stein. Sunday slow morning, home by afternoon.',
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Coshocton%2C+Ohio',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Roscoe_Village_from_the_south.jpg/960px-Roscoe_Village_from_the_south.jpg',
  },
  {
    id: 'put-in-bay',
    name: 'Put-in-Bay',
    state: 'OH',
    driveHours: 3,
    drive_minutes: 180,
    drive_from_fort_wayne: '3 hrs',
    hook: 'A Lake Erie island reached by ferry, with a 352-foot granite column, golf carts for rent, and zero agenda.',
    anchor_name: "Perry's Victory Monument",
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Nature', 'History', 'Quirky', 'Water'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Perry%27s_Victory_and_International_Peace_Memorial_%284663688070%29.jpg/960px-Perry%27s_Victory_and_International_Peace_Memorial_%284663688070%29.jpg',
  },
  {
    id: 'cleveland',
    name: 'Cleveland',
    state: 'OH',
    driveHours: 3,
    drive_minutes: 180,
    drive_from_fort_wayne: '3 hrs',
    hook: 'Underrated in the best way — a waterfront city with a chip on its shoulder and a lot of surprises.',
    anchor_name: 'Rock & Roll Hall of Fame',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['History', 'Arts', 'Music'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Cleveland_skyline_from_Lakewood_Park%2C_January_2026.jpg/960px-Cleveland_skyline_from_Lakewood_Park%2C_January_2026.jpg',
  },
  {
    id: 'french-lick',
    name: 'French Lick',
    state: 'IN',
    driveHours: 3,
    drive_minutes: 180,
    drive_from_fort_wayne: '3 hrs',
    hook: "The dome at West Baden Springs Hotel was called the Eighth Wonder of the World when it was finished in 1902 — a freestanding atrium as wide as the Pantheon, in a small Indiana town where people used to drink sulfur water. The strangeness is the point.",
    anchor_name: 'West Baden Springs Hotel',
    anchor_description: "Built in 1902 as a resort for people taking mineral water cures, the West Baden dome spans 200 feet without interior support — larger than the Pantheon. It sat abandoned for 50 years, nearly demolished twice, and reopened in 2007 after a $35 million restoration.",
    anchor_address: '8538 W Baden Ave, West Baden Springs, IN 47469',
    anchor_hours: 'Lobby and atrium open to visitors daily; guided tours available',
    anchor_cost: 'Free to walk through the atrium; guided tours $10–15/person',
    tags: ['History', 'Quirky', 'Arts'],
    vibe: "A little faded, a little grand, genuinely eccentric. The casino money brought the resort back, but the West Baden dome is the real thing — dusty glamour that got a second life. Larry Bird grew up nearby; the locals are quietly proud.",
    best_season: 'Year-round',
    estimated_cost_low: 100,
    estimated_cost_high: 280,
    where_to_stay: "West Baden Springs Hotel if the budget allows — staying inside the dome is the whole point. French Lick Springs Hotel (the casino property, connected by trolley) is the flashier option. Airbnbs in Springs Valley for budget stays.",
    food_picks: [
      "1875 by Larry Bird — steakhouse at French Lick Resort, the best dinner option in the area",
      "The Sinclair — hotel restaurant at West Baden, solid for breakfast before exploring the grounds",
      "Hoosier Restaurant in French Lick — local diner, nothing fancy, that's exactly the point",
    ],
    other_stops: [
      "French Lick Scenic Railway — vintage train through the Hoosier National Forest, seasonal (book ahead)",
      'Pluto Water building — where the famous sulfur mineral water was bottled and sold nationally; you can still find the bottles',
      "French Lick Casino — attached to the resort, 24/7 if that's your thing",
      'Patoka Lake — 20 miles east, 26,000 acres of water and trails, good for a morning hike',
    ],
    suggested_order: "Arrive Friday evening. Walk the West Baden dome immediately — it hits differently when there are fewer people around. Saturday: scenic railway in the morning (book ahead online). Afternoon: Pluto Water history, walk downtown French Lick. Dinner at 1875. Sunday: Patoka Lake if the weather holds, then the long drive back north.",
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=French+Lick%2C+Indiana',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/West_Baden_Springs_Hotel%2C_2024.jpg/960px-West_Baden_Springs_Hotel%2C_2024.jpg',
  },
  {
    id: 'galena',
    name: 'Galena',
    state: 'IL',
    driveHours: 3.5,
    drive_minutes: 210,
    drive_from_fort_wayne: '3.5 hrs',
    hook: "A perfectly preserved 1850s Main Street where 85% of the buildings are on the National Register of Historic Places, antique shops that actually have good stuff, and rolling Illinois hill country you didn't know existed.",
    anchor_name: "Ulysses S. Grant's Home",
    anchor_description: "The Italianate house given to Grant after the Civil War, still furnished as it was when he lived there. But the bigger draw is the Main Street itself — unchanged since the lead-mining boom ended and the town simply stopped developing.",
    anchor_address: '500 Bouthillier St, Galena, IL 61036',
    anchor_hours: 'Wed–Sun 9am–4:45pm; closed Mon–Tue and major holidays',
    anchor_cost: 'Free (donations welcome)',
    tags: ['History', 'Quirky', 'Arts'],
    vibe: "Well-preserved and knows it, but not in a museum way. Main Street genuinely looks like the 1850s. Wine country on the edges, antiques in every direction. More sophisticated than you'd expect this far from Chicago.",
    best_season: 'Fall (peak leaf season), Summer (busiest), Spring (quieter and cheaper)',
    estimated_cost_low: 100,
    estimated_cost_high: 220,
    where_to_stay: "DeSoto House Hotel — operating since 1855, right on Main Street. Abraham Lincoln and Mark Twain both stayed here. B&Bs throughout town. Eagle Ridge Resort 10 min out for a bigger property.",
    food_picks: [
      "Fried Green Tomatoes — the best restaurant in Galena, Italian-American, worth making a reservation the evening before you go",
      "Otto's Place — casual breakfast and lunch, where locals actually eat",
      'Galena Brewing Company — solid local beer downtown, good for a late afternoon pint after the antique shops',
    ],
    other_stops: [
      "Belvedere Mansion — 1857 Italianate mansion with original Victorian furnishings, one of the best house tours in Illinois",
      'Jo Daviess County wine trail — several small wineries in the surrounding hills, good for a Sunday afternoon',
      "Chestnut Mountain Resort — skiing in winter, views year-round, 8 miles from downtown",
      'Galena River Trail — 6-mile paved path through the river valley, easy and scenic',
    ],
    suggested_order: "Arrive Friday evening. Main Street dinner — walk it first, then eat at Fried Green Tomatoes if you have a reservation. Saturday: Grant Home in the morning (free, better than expected). Antique shops all afternoon — budget serious time for this. Sunday: Belvedere Mansion tour, then one winery on the way out of town.",
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Galena%2C+Illinois',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Galena%2C_Illinois.jpg/960px-Galena%2C_Illinois.jpg',
  },
  {
    id: 'sleeping-bear-dunes',
    name: 'Sleeping Bear Dunes',
    state: 'MI',
    driveHours: 3.5,
    drive_minutes: 210,
    drive_from_fort_wayne: '3.5 hrs',
    hook: 'You climb a sand mountain, your legs give out, and the reward is a view of Lake Michigan that looks like the ocean.',
    anchor_name: '450-Ft Sand Dunes over Lake Michigan',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Nature', 'Quirky', 'Water'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Dunes_and_fog_from_Platte_Point_%2895c5ad13-5f8a-4a59-838f-50b9a644648c%29.jpg/960px-Dunes_and_fog_from_Platte_Point_%2895c5ad13-5f8a-4a59-838f-50b9a644648c%29.jpg',
  },
  {
    id: 'mackinac-island',
    name: 'Mackinac Island',
    state: 'MI',
    driveHours: 4.5,
    drive_minutes: 270,
    drive_from_fort_wayne: '4.5 hrs',
    hook: "No cars allowed — Michigan banned them in 1898 and it stuck. Arrive by ferry, get around by horse or bike, eat more fudge than you planned to, and be on the island when the day-trip boats have gone back.",
    anchor_name: 'A Car-Free Island Frozen in 1898',
    anchor_description: "4.35 square miles of island in the Straits of Mackinac, navigated entirely by bicycle, horse-drawn carriage, or foot. Fort Mackinac has stood since 1780. The Grand Hotel's porch is the longest in the world.",
    anchor_address: 'Take the ferry from Mackinaw City or St. Ignace, MI (~15 min crossing)',
    anchor_hours: 'Island accessible May–October; ferry runs seasonally; some shops and hotels open year-round',
    anchor_cost: 'Ferry ~$30 round trip/person; bike rental $10–15/hr or $30/day',
    tags: ['Nature', 'History', 'Quirky', 'Food', 'Water'],
    vibe: "Genuinely magical and just kitschy enough to be charming. No cars means it's quiet except for hoofbeats and bike bells. The fudge shops are unabashedly tourist-trap and somehow still fun. Going for at least one night is not optional — morning on the island before the day boats arrive is the whole point.",
    best_season: 'June–September (peak); May and October are quieter and cheaper',
    estimated_cost_low: 160,
    estimated_cost_high: 380,
    where_to_stay: "Mission Point Resort — great views of the Straits, good value compared to the Grand Hotel. Iroquois Hotel for small and historic. Grand Hotel if budget isn't a constraint — it's genuinely grand and worth it once.",
    food_picks: [
      "Ryba's Fudge — the classic island fudge shop. Watching them pour and work it on the marble slab is half the experience. Get the chocolate walnut.",
      "The Pink Pony — burgers and cocktails with water views, the best casual dinner on the island",
      'Seabiscuit Cafe — good casual breakfast, right pace for a slow morning start',
    ],
    other_stops: [
      "Fort Mackinac — British fort from 1780, history and cannon demonstrations, views over the Straits",
      'Arch Rock — natural limestone arch 150 feet above the water, easy hike, genuinely dramatic',
      "Grand Hotel porch — $5 to walk it (non-guests), worth it for the views. Afternoon tea available.",
      "Biking the perimeter road — 8 miles around the entire island, one of the best ways to see it all",
    ],
    suggested_order: "Take the morning ferry from Mackinaw City. Check in and rent bikes immediately. Ride the perimeter road (8 miles, 1-2 hours). Stop at Arch Rock. Afternoon: Fort Mackinac, fudge stop (mandatory). Dinner at the Pink Pony. Next morning: wake up before the boats arrive — the early quiet is the whole reason to stay overnight. Seabiscuit Cafe breakfast, walk the Grand Hotel porch. Ferry back by noon.",
    booking_search_url: 'https://www.booking.com/searchresults.html?ss=Mackinac+Island%2C+Michigan',
    region: 'Midwest',
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Mackinac_Island%27s_main_town%2C_looking_west._Transportation_on_the_island_is_by_horse%2C_bike%2C_or_foot..jpg/960px-Mackinac_Island%27s_main_town%2C_looking_west._Transportation_on_the_island_is_by_horse%2C_bike%2C_or_foot..jpg",
  },
  {
    id: 'nashville',
    name: 'Nashville',
    state: 'TN',
    driveHours: 5,
    drive_minutes: 300,
    drive_from_fort_wayne: '5 hrs',
    hook: 'Live music spilling out of every door, hot chicken that earns its reputation, and a city that never really sleeps.',
    anchor_name: 'Honky-Tonk Row on Broadway',
    anchor_description: '',
    anchor_address: '',
    anchor_hours: '',
    anchor_cost: '',
    tags: ['Music', 'Food', 'Arts'],
    vibe: '',
    best_season: '',
    estimated_cost_low: null,
    estimated_cost_high: null,
    where_to_stay: '',
    food_picks: [],
    other_stops: [],
    suggested_order: '',
    booking_search_url: '',
    region: 'Midwest',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nashville%2C_TN_skyline.jpg/960px-Nashville%2C_TN_skyline.jpg',
  },
];
